# .travis.yml


language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"  
  # - hhvm

env:

before_script:
  - rm composer.lock
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cp phpunit.xml.dist phpunit.xml

script:
  - composer test

after_script:

