language: php
php:
  - "5.6"
  - "7.0"
  - "7.1"
  - hhvm

env:

before_script:
  - cp phpunit.xml.dist phpunit.xml
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

after_script:

