# .travis.yml

language: php

php:
  - "7.3"
  - "7.4"
  - "8.0"

env:

before_script:
  - rm composer.lock
  - composer self-update
  - composer install --no-interaction
  - cp phpunit.xml.dist phpunit.xml

script:
  - composer phpunit

after_script:
